### ISSUE TITLE
Maximum call stack size exceeded when template has values in it

### ISSUE THREAD

**Issue by zapphyre** [asteridux/skorice#2]
When you try to assert on template that is having non-empty key-VALUES pairs, it ends with error:
```

RangeError: Maximum call stack size exceeded
    at templateKeys.forEach.key (node_modules/skorice/build/lib.js:41:24)
    at Array.forEach (<anonymous>)
    at objectWalker (node_modules/skorice/build/lib.js:41:16)
    at templateKeys.forEach.key (node_modules/skorice/build/lib.js:43:23)
    at Array.forEach (<anonymous>)
    at objectWalker (node_modules/skorice/build/lib.js:41:16)
    at templateKeys.forEach.key (node_modules/skorice/build/lib.js:43:23)
    at Array.forEach (<anonymous>)
```

I think, this will be the same as [this issue](https://github.com/AntJanus/JSON-structure-validator/issues/6) ;)

**Comment by AntJanus** [comment]
@zapphyre I'll port over the fix from https://github.com/AntJanus/JSON-structure-validator/issues/6#issuecomment-338659634 Thank you! :)
